name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - 'android/.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - 'android/.editorconfig'

jobs:
  KTLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download ktlint
        working-directory: ./android/
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.1.1/ktlint
          chmod a+x ktlint
      - name: Run ktlint
        working-directory: ./android/
        run: |
          ./ktlint --reporter=checkstyle,output=build/ktlint-report.xml --relative --editorconfig=./.editorconfig
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: ./android/build/*.xml
        continue-on-error: false
      - uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: ./android/build/*.xml
